export const variables = {
  colorPrimary: '#000',
  mainSpacing: '10px',
  smallSpacing: '5px',
  bigSpacing: '20px',
  biggerSpacing: '40px',
  mainPadding: '10px',
  colorBackground: '#d6d6d6',
  colorBackgroundBox: '#fff',
  colorDanger: '#eb4034',
  colorFont: '#000',
  colorBorder: '#dedede',
  borderRadius: '6px',
  colorAccent: '#1ced88',
  headerHeight: '2rem',
};
